params:
  objective: "regression"
  boosting: "dart"
  learning_rate: 0.01
  num_leaves: 20
  feature_fraction: 0.50
  bagging_fraction: 0.50
  bagging_freq: 5
  min_data_in_leaf: 3
  lambda_l1: 0.01
  lambda_l2: 10
  # other
  seed: 42
  # metric
  metric: ["l2"]

  #early_stopping_rounds: 5
train_kargs:
  num_boost_round: 2000

target: funding_rate_future_5
categorical_feature:
  - dt__day_of_week
  - dt__day_of_month
  - dt__hour
  # - fear_and_greed_class
features:
  # category
  # - symbol_id
  # datetime
  - dt__day_of_week
  - dt__day_of_month
  - dt__hour
  - dt__is_quarter_start
  - dt__is_quarter_end
  - dt__is_month_start
  - dt__is_month_end
  - dt__is_weekend
  # fear & greed
  - fear_and_greed_value
  # - fear_and_greed_class
  # numerical
  - funding_rate
  - funding_rate__lag1
  - funding_rate__lag3
  - funding_rate__lag5
  - funding_rate__diff1
  - funding_rate__diff3
  - funding_rate__diff5
  ##
  - index_price
  - mark_price
  - price_diff
  ##
  - funding_rate_expcumsum_0.5
  - funding_rate_expcumsum_1
  - funding_rate_expcumsum_2
  - funding_rate_expcumsum_3
  - funding_rate_expcumsum_5
  - funding_rate_expcumsum_10
  - funding_rate_expcumsum_20
  - funding_rate_rol_mean_3
  - funding_rate_rol_std_3
  - funding_rate_rol_max_3
  - funding_rate_rol_min_3
  - funding_rate_rol_skew_3
  - funding_rate_rol_mean_5
  - funding_rate_rol_std_5
  - funding_rate_rol_max_5
  - funding_rate_rol_min_5
  - funding_rate_rol_skew_5
  - funding_rate_rol_kurt_5
  - funding_rate_rol_mean_10
  - funding_rate_rol_std_10
  - funding_rate_rol_max_10
  - funding_rate_rol_min_10
  - funding_rate_rol_skew_10
  - funding_rate_rol_kurt_10
  - funding_rate_rol_mean_20
  - funding_rate_rol_std_20
  - funding_rate_rol_max_20
  - funding_rate_rol_min_20
  - funding_rate_rol_skew_20
  - funding_rate_rol_kurt_20
  - index_price_expcumsum_0.5
  - index_price_expcumsum_1
  - index_price_expcumsum_2
  - index_price_expcumsum_3
  - index_price_expcumsum_5
  - index_price_expcumsum_10
  - index_price_expcumsum_20
  - index_price_rol_mean_3
  - index_price_rol_std_3
  - index_price_rol_max_3
  - index_price_rol_min_3
  - index_price_rol_skew_3
  - index_price_rol_mean_5
  - index_price_rol_std_5
  - index_price_rol_max_5
  - index_price_rol_min_5
  - index_price_rol_skew_5
  - index_price_rol_kurt_5
  - index_price_rol_mean_10
  - index_price_rol_std_10
  - index_price_rol_max_10
  - index_price_rol_min_10
  - index_price_rol_skew_10
  - index_price_rol_kurt_10
  - index_price_rol_mean_20
  - index_price_rol_std_20
  - index_price_rol_max_20
  - index_price_rol_min_20
  - index_price_rol_skew_20
  - index_price_rol_kurt_20
  - mark_price_expcumsum_0.5
  - mark_price_expcumsum_1
  - mark_price_expcumsum_2
  - mark_price_expcumsum_3
  - mark_price_expcumsum_5
  - mark_price_expcumsum_10
  - mark_price_expcumsum_20
  - mark_price_rol_mean_3
  - mark_price_rol_std_3
  - mark_price_rol_max_3
  - mark_price_rol_min_3
  - mark_price_rol_skew_3
  - mark_price_rol_mean_5
  - mark_price_rol_std_5
  - mark_price_rol_max_5
  - mark_price_rol_min_5
  - mark_price_rol_skew_5
  - mark_price_rol_kurt_5
  - mark_price_rol_mean_10
  - mark_price_rol_std_10
  - mark_price_rol_max_10
  - mark_price_rol_min_10
  - mark_price_rol_skew_10
  - mark_price_rol_kurt_10
  - mark_price_rol_mean_20
  - mark_price_rol_std_20
  - mark_price_rol_max_20
  - mark_price_rol_min_20
  - mark_price_rol_skew_20
  - mark_price_rol_kurt_20

symbols:
  - 1INCHUSDT
  - MKRUSDT
  - ALICEUSDT
  - COMPUSDT
  - RENUSDT
  - FTMUSDT
  - ETCUSDT
  - BCHUSDT
  - SOLUSDT
  - HNTUSDT
  - WAVESUSDT
  - ADAUSDT
  - ROSEUSDT
  - OGNUSDT
  - PEOPLEUSDT
  - LINKUSDT
  - NEARUSDT
  - AVAXUSDT
  - EGLDUSDT
  - BALUSDT
  - SOLBUSD
  - ALPHAUSDT
  - ATOMUSDT
