name: aura
dependencies:
  - python=3.9
  # data
  - conda-forge::pyarrow
  - scikit-learn
  - pandas
  # tools
  - pyyaml
  - ipykernel
  - tqdm
  - conda-forge::black
  - conda-forge::gitpython
  # training
  - lightgbm
  - conda-forge::tensorflow=2.7.0
  - conda-forge::optuna
  # analysis
  - conda-forge::shap
  # visualize
  - conda-forge::matplotlib
  - anaconda::seaborn
